[aws]
app_machine ansible_host=107.23.4.68 ansible_user=ubuntu ansible_ssh_private_key_file=~/capstone-key.pem

[azure]
azure_vm ansible_host=20.127.104.55 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
